export const massiveRealColleges = [
  // MYSURU
  {
    name: 'Sri Jayachamarajendra College of Engineering (SJCE)',
    district: 'Mysuru',
    city: 'Mysuru',
    categories: ['Engineering'],
    type: 'Private',
    ownership: 'Private',
    courses: ['B.E', 'M.Tech', 'MCA'],
    specializations: ['Computer Science', 'Electronics', 'Mechanical', 'Civil'],
    fees: { tuition: '1L - 4L' },
    placement: { percentage: 95, avgPackage: '8 LPA' },
    nirfRank: 150,
    website: 'sjce.ac.in',
    sourceId: 'sjce-mys'
  },
  {
    name: 'Mysore Medical College and Research Institute (MMCRI)',
    district: 'Mysuru',
    city: 'Mysuru',
    categories: ['Medical'],
    type: 'Government',
    ownership: 'Government',
    courses: ['MBBS', 'MD', 'MS'],
    specializations: ['General Medicine', 'Surgery', 'Pediatrics'],
    fees: { tuition: '60K' },
    placement: { percentage: 100, avgPackage: '10 LPA' },
    nirfRank: 40,
    website: 'mysoremedicalcollege.edu.in',
    sourceId: 'mmcri-mys'
  },
  {
    name: 'National Institute of Engineering (NIE)',
    district: 'Mysuru',
    city: 'Mysuru',
    categories: ['Engineering'],
    type: 'Private',
    ownership: 'Private',
    courses: ['B.E', 'M.Tech'],
    specializations: ['Information Science', 'Mechanical', 'Civil'],
    fees: { tuition: '1L - 3L' },
    placement: { percentage: 90, avgPackage: '6.5 LPA' },
    nirfRank: 175,
    website: 'nie.ac.in',
    sourceId: 'nie-mys'
  },
  {
    name: 'JSS Medical College',
    district: 'Mysuru',
    city: 'Mysuru',
    categories: ['Medical'],
    type: 'Private',
    ownership: 'Private',
    courses: ['MBBS', 'BDS', 'Pharmacy'],
    specializations: ['Medicine', 'Dentistry', 'Pharm.D'],
    fees: { tuition: '15L - 20L' },
    placement: { percentage: 98, avgPackage: '12 LPA' },
    nirfRank: 34,
    website: 'jssuni.edu.in',
    sourceId: 'jss-mys'
  },
  
  // DAKSHINA KANNADA (MANGALURU)
  {
    name: 'National Institute of Technology Karnataka (NITK)',
    district: 'Dakshina Kannada',
    city: 'Surathkal',
    categories: ['Engineering', 'Management', 'Science'],
    type: 'Government',
    ownership: 'Government',
    courses: ['B.Tech', 'M.Tech', 'MBA', 'MCA'],
    specializations: ['Computer Science', 'Chemical', 'Mining', 'Mechanical'],
    fees: { tuition: '1.5L - 2L' },
    placement: { percentage: 98, avgPackage: '18 LPA' },
    nirfRank: 12,
    website: 'nitk.ac.in',
    sourceId: 'nitk-sur'
  },
  {
    name: 'Kasturba Medical College (KMC)',
    district: 'Dakshina Kannada',
    city: 'Mangaluru',
    categories: ['Medical'],
    type: 'Private',
    ownership: 'Private',
    courses: ['MBBS', 'MD'],
    specializations: ['Medicine', 'Surgery', 'Anatomy'],
    fees: { tuition: '18L - 22L' },
    placement: { percentage: 100, avgPackage: '15 LPA' },
    nirfRank: 30,
    website: 'manipal.edu/kmc-mangaluru',
    sourceId: 'kmc-man'
  },
  {
    name: 'St. Aloysius College',
    district: 'Dakshina Kannada',
    city: 'Mangaluru',
    categories: ['Science', 'Commerce', 'Management'],
    type: 'Private',
    ownership: 'Private',
    courses: ['B.Sc', 'B.Com', 'BBA'],
    specializations: ['Computer Science', 'Finance', 'Marketing'],
    fees: { tuition: '40K - 80K' },
    placement: { percentage: 80, avgPackage: '4 LPA' },
    nirfRank: 80,
    website: 'staloysius.edu.in',
    sourceId: 'aloysius-man'
  },

  // BELAGAVI
  {
    name: 'KLE Technological University',
    district: 'Belagavi',
    city: 'Belagavi',
    categories: ['Engineering', 'Management'],
    type: 'Private',
    ownership: 'Private',
    courses: ['B.E', 'M.Tech', 'MBA'],
    specializations: ['Automation', 'Robotics', 'CSE'],
    fees: { tuition: '2L - 3L' },
    placement: { percentage: 85, avgPackage: '6 LPA' },
    nirfRank: 200,
    website: 'kletech.ac.in',
    sourceId: 'kle-bel'
  },
  {
    name: 'Jawaharlal Nehru Medical College (JNMC)',
    district: 'Belagavi',
    city: 'Belagavi',
    categories: ['Medical'],
    type: 'Private',
    ownership: 'Private',
    courses: ['MBBS', 'MD', 'MS'],
    specializations: ['Pediatrics', 'Surgery'],
    fees: { tuition: '15L - 18L' },
    placement: { percentage: 95, avgPackage: '12 LPA' },
    nirfRank: 42,
    website: 'jnmc.edu',
    sourceId: 'jnmc-bel'
  },

  // DHARWAD (HUBBALLI)
  {
    name: 'B.V. Bhoomaraddi College of Engineering and Technology (BVB)',
    district: 'Dharwad',
    city: 'Hubballi',
    categories: ['Engineering'],
    type: 'Private',
    ownership: 'Private',
    courses: ['B.E', 'B.Arch'],
    specializations: ['Architecture', 'CSE', 'Civil'],
    fees: { tuition: '1.5L - 3L' },
    placement: { percentage: 88, avgPackage: '5.5 LPA' },
    nirfRank: 190,
    website: 'kletech.ac.in/bvb',
    sourceId: 'bvb-hub'
  },
  {
    name: 'Karnataka Institute of Medical Sciences (KIMS)',
    district: 'Dharwad',
    city: 'Hubballi',
    categories: ['Medical'],
    type: 'Government',
    ownership: 'Government',
    courses: ['MBBS', 'Nursing'],
    specializations: ['General Medicine', 'Nursing'],
    fees: { tuition: '50K' },
    placement: { percentage: 100, avgPackage: '8 LPA' },
    nirfRank: 80,
    website: 'kimshubballi.org',
    sourceId: 'kims-hub'
  },
  {
    name: 'Indian Institute of Technology (IIT) Dharwad',
    district: 'Dharwad',
    city: 'Dharwad',
    categories: ['Engineering'],
    type: 'Government',
    ownership: 'Government',
    courses: ['B.Tech', 'M.Tech', 'Ph.D'],
    specializations: ['Computer Science', 'Electrical', 'Mechanical'],
    fees: { tuition: '2L' },
    placement: { percentage: 100, avgPackage: '16 LPA' },
    nirfRank: 93,
    website: 'iitdh.ac.in',
    sourceId: 'iit-dharwad'
  },

  // TUMAKURU
  {
    name: 'Siddaganga Institute of Technology (SIT)',
    district: 'Tumakuru',
    city: 'Tumakuru',
    categories: ['Engineering', 'Management'],
    type: 'Private',
    ownership: 'Private',
    courses: ['B.E', 'M.Tech', 'MBA'],
    specializations: ['CSE', 'Information Science', 'Chemical'],
    fees: { tuition: '1.5L - 3.5L' },
    placement: { percentage: 90, avgPackage: '7 LPA' },
    nirfRank: 97,
    website: 'sit.ac.in',
    sourceId: 'sit-tum'
  },
  {
    name: 'Sri Siddhartha Medical College',
    district: 'Tumakuru',
    city: 'Tumakuru',
    categories: ['Medical'],
    type: 'Private',
    ownership: 'Private',
    courses: ['MBBS', 'MD'],
    specializations: ['Medicine', 'Surgery'],
    fees: { tuition: '12L - 16L' },
    placement: { percentage: 90, avgPackage: '9 LPA' },
    nirfRank: 110,
    website: 'ssmctumkur.org',
    sourceId: 'ssmc-tum'
  },

  // UDUPI
  {
    name: 'Manipal Institute of Technology (MIT)',
    district: 'Udupi',
    city: 'Manipal',
    categories: ['Engineering'],
    type: 'Private',
    ownership: 'Private',
    courses: ['B.Tech', 'M.Tech'],
    specializations: ['Computer Science', 'Mechatronics', 'Aeronautical'],
    fees: { tuition: '4L - 5L' },
    placement: { percentage: 95, avgPackage: '12.5 LPA' },
    nirfRank: 61,
    website: 'manipal.edu/mit',
    sourceId: 'mit-manipal'
  },
  {
    name: 'Manipal College of Dental Sciences',
    district: 'Udupi',
    city: 'Manipal',
    categories: ['Medical'],
    type: 'Private',
    ownership: 'Private',
    courses: ['BDS', 'MDS'],
    specializations: ['Dentistry', 'Orthodontics'],
    fees: { tuition: '6L - 8L' },
    placement: { percentage: 98, avgPackage: '8 LPA' },
    nirfRank: 2, 
    website: 'manipal.edu/mcods',
    sourceId: 'mcods-manipal'
  },
  
  // HASSAN
  {
    name: 'Malnad College of Engineering (MCE)',
    district: 'Hassan',
    city: 'Hassan',
    categories: ['Engineering'],
    type: 'Private',
    ownership: 'Private',
    courses: ['B.E', 'M.Tech'],
    specializations: ['Civil', 'Mechanical', 'CSE'],
    fees: { tuition: '1L - 2.5L' },
    placement: { percentage: 80, avgPackage: '5 LPA' },
    nirfRank: 200,
    website: 'mcehassan.ac.in',
    sourceId: 'mce-hassan'
  },
  {
    name: 'Hassan Institute of Medical Sciences (HIMS)',
    district: 'Hassan',
    city: 'Hassan',
    categories: ['Medical'],
    type: 'Government',
    ownership: 'Government',
    courses: ['MBBS'],
    specializations: ['General Medicine'],
    fees: { tuition: '60K' },
    placement: { percentage: 100, avgPackage: '8 LPA' },
    nirfRank: null,
    website: 'hims-hassan.org',
    sourceId: 'hims-hassan'
  },

  // MANDYA
  {
    name: 'PES College of Engineering',
    district: 'Mandya',
    city: 'Mandya',
    categories: ['Engineering'],
    type: 'Private',
    ownership: 'Private',
    courses: ['B.E', 'M.Tech'],
    specializations: ['Automobile', 'CSE', 'ECE'],
    fees: { tuition: '1L - 2.5L' },
    placement: { percentage: 75, avgPackage: '4.5 LPA' },
    nirfRank: 161,
    website: 'pescemandya.org',
    sourceId: 'pesce-mandya'
  },
  {
    name: 'Mandya Institute of Medical Sciences (MIMS)',
    district: 'Mandya',
    city: 'Mandya',
    categories: ['Medical'],
    type: 'Government',
    ownership: 'Government',
    courses: ['MBBS'],
    specializations: ['General Medicine'],
    fees: { tuition: '60K' },
    placement: { percentage: 100, avgPackage: '8 LPA' },
    nirfRank: null,
    website: 'mimsmandya.org',
    sourceId: 'mims-mandya'
  },

  // SHIVAMOGGA
  {
    name: 'Jawaharlal Nehru National College of Engineering (JNNCE)',
    district: 'Shivamogga',
    city: 'Shivamogga',
    categories: ['Engineering'],
    type: 'Private',
    ownership: 'Private',
    courses: ['B.E', 'M.Tech', 'MBA'],
    specializations: ['CSE', 'Civil', 'Mechanical'],
    fees: { tuition: '1L - 3L' },
    placement: { percentage: 70, avgPackage: '4 LPA' },
    nirfRank: 250,
    website: 'jnnce.ac.in',
    sourceId: 'jnnce-shiv'
  },
  {
    name: 'Shivamogga Institute of Medical Sciences (SIMS)',
    district: 'Shivamogga',
    city: 'Shivamogga',
    categories: ['Medical'],
    type: 'Government',
    ownership: 'Government',
    courses: ['MBBS'],
    specializations: ['General Medicine'],
    fees: { tuition: '60K' },
    placement: { percentage: 100, avgPackage: '8 LPA' },
    nirfRank: null,
    website: 'sims-shivamogga.org',
    sourceId: 'sims-shiv'
  },

  // KALABURAGI
  {
    name: 'PDA College of Engineering',
    district: 'Kalaburagi',
    city: 'Kalaburagi',
    categories: ['Engineering'],
    type: 'Private',
    ownership: 'Private',
    courses: ['B.E', 'B.Arch'],
    specializations: ['Civil', 'Architecture', 'CSE'],
    fees: { tuition: '1L - 2.5L' },
    placement: { percentage: 65, avgPackage: '3.5 LPA' },
    nirfRank: null,
    website: 'pdaengg.com',
    sourceId: 'pda-kal'
  },
  {
    name: 'Gulbarga Institute of Medical Sciences (GIMS)',
    district: 'Kalaburagi',
    city: 'Kalaburagi',
    categories: ['Medical'],
    type: 'Government',
    ownership: 'Government',
    courses: ['MBBS'],
    specializations: ['General Medicine'],
    fees: { tuition: '60K' },
    placement: { percentage: 100, avgPackage: '8 LPA' },
    nirfRank: null,
    website: 'gims-kalaburagi.org',
    sourceId: 'gims-kal'
  },

  // BALLARI
  {
    name: 'Rao Bahadur Y Mahabaleswarappa Engineering College (RYMEC)',
    district: 'Ballari',
    city: 'Ballari',
    categories: ['Engineering'],
    type: 'Private',
    ownership: 'Private',
    courses: ['B.E', 'MBA'],
    specializations: ['CSE', 'ECE', 'Mechanical'],
    fees: { tuition: '1L - 2L' },
    placement: { percentage: 60, avgPackage: '3 LPA' },
    nirfRank: null,
    website: 'rymec.in',
    sourceId: 'rymec-ballari'
  },
  {
    name: 'Vijayanagar Institute of Medical Sciences (VIMS)',
    district: 'Ballari',
    city: 'Ballari',
    categories: ['Medical'],
    type: 'Government',
    ownership: 'Government',
    courses: ['MBBS', 'Nursing'],
    specializations: ['Medicine', 'Nursing'],
    fees: { tuition: '60K' },
    placement: { percentage: 100, avgPackage: '8 LPA' },
    nirfRank: null,
    website: 'vimsbellary.org',
    sourceId: 'vims-ballari'
  },

  // DAVANAGERE
  {
    name: 'Bapuji Institute of Engineering and Technology (BIET)',
    district: 'Davanagere',
    city: 'Davanagere',
    categories: ['Engineering'],
    type: 'Private',
    ownership: 'Private',
    courses: ['B.E', 'M.Tech'],
    specializations: ['Textile', 'CSE', 'Biotechnology'],
    fees: { tuition: '1.5L - 3L' },
    placement: { percentage: 75, avgPackage: '4.5 LPA' },
    nirfRank: null,
    website: 'bietdvg.edu',
    sourceId: 'biet-dvg'
  },
  {
    name: 'JJM Medical College',
    district: 'Davanagere',
    city: 'Davanagere',
    categories: ['Medical'],
    type: 'Private',
    ownership: 'Private',
    courses: ['MBBS', 'MD'],
    specializations: ['Medicine', 'Surgery'],
    fees: { tuition: '10L - 15L' },
    placement: { percentage: 95, avgPackage: '9 LPA' },
    nirfRank: null,
    website: 'jjmmc.org',
    sourceId: 'jjmmc-dvg'
  },

  // RAICHUR
  {
    name: 'Raichur Institute of Medical Sciences (RIMS)',
    district: 'Raichur',
    city: 'Raichur',
    categories: ['Medical'],
    type: 'Government',
    ownership: 'Government',
    courses: ['MBBS'],
    specializations: ['General Medicine'],
    fees: { tuition: '60K' },
    placement: { percentage: 100, avgPackage: '8 LPA' },
    nirfRank: null,
    website: 'rims-raichur.com',
    sourceId: 'rims-raichur'
  },

  // VIJAYAPURA
  {
    name: 'BLDE Association’s Vachana Pitamaha Dr. P.G. Halakatti College of Engineering and Technology',
    district: 'Vijayapura',
    city: 'Vijayapura',
    categories: ['Engineering'],
    type: 'Private',
    ownership: 'Private',
    courses: ['B.E', 'M.Tech'],
    specializations: ['Civil', 'CSE', 'ECE'],
    fees: { tuition: '1L - 2.5L' },
    placement: { percentage: 70, avgPackage: '4 LPA' },
    nirfRank: null,
    website: 'bldeacet.ac.in',
    sourceId: 'blde-vij'
  },
  {
    name: 'Al-Ameen Medical College',
    district: 'Vijayapura',
    city: 'Vijayapura',
    categories: ['Medical'],
    type: 'Private',
    ownership: 'Private',
    courses: ['MBBS'],
    specializations: ['General Medicine'],
    fees: { tuition: '8L - 12L' },
    placement: { percentage: 90, avgPackage: '7 LPA' },
    nirfRank: null,
    website: 'alameenmedical.org',
    sourceId: 'alameen-vij'
  },

  // CHIKKABALLAPUR
  {
    name: 'SJB Institute of Technology (SJBIT) - Muddenahalli Campus',
    district: 'Chikkaballapur',
    city: 'Chikkaballapur',
    categories: ['Engineering'],
    type: 'Private',
    ownership: 'Private',
    courses: ['B.E'],
    specializations: ['CSE', 'ECE'],
    fees: { tuition: '1.5L - 3L' },
    placement: { percentage: 80, avgPackage: '5 LPA' },
    nirfRank: null,
    website: 'sjbit.edu.in',
    sourceId: 'sjbit-chik'
  },
  {
    name: 'Chikkaballapur Institute of Medical Sciences (CIMS)',
    district: 'Chikkaballapur',
    city: 'Chikkaballapur',
    categories: ['Medical'],
    type: 'Government',
    ownership: 'Government',
    courses: ['MBBS'],
    specializations: ['General Medicine'],
    fees: { tuition: '60K' },
    placement: { percentage: 100, avgPackage: '8 LPA' },
    nirfRank: null,
    website: 'cimschikkaballapur.org',
    sourceId: 'cims-chik'
  },
  
  // DIPLOMA & ITI & VOCATIONAL (Cross-district representation)
  {
    name: 'Government Polytechnic, Mysuru',
    district: 'Mysuru',
    city: 'Mysuru',
    categories: ['Diploma', 'Polytechnic'],
    type: 'Government',
    ownership: 'Government',
    courses: ['Diploma'],
    specializations: ['Civil', 'Mechanical', 'Electrical'],
    fees: { tuition: '5K - 10K' },
    placement: { percentage: 60, avgPackage: '2 LPA' },
    nirfRank: null,
    website: 'gptmysuru.in',
    sourceId: 'gpt-mys'
  },
  {
    name: 'Government ITI, Hubballi',
    district: 'Dharwad',
    city: 'Hubballi',
    categories: ['ITI', 'Vocational'],
    type: 'Government',
    ownership: 'Government',
    courses: ['ITI'],
    specializations: ['Fitter', 'Electrician', 'Welder'],
    fees: { tuition: '2K - 5K' },
    placement: { percentage: 70, avgPackage: '1.5 LPA' },
    nirfRank: null,
    website: 'giti-hubballi.in',
    sourceId: 'giti-hub'
  },
  {
    name: 'MEI Polytechnic',
    district: 'Bengaluru Urban',
    city: 'Bengaluru',
    categories: ['Diploma', 'Polytechnic'],
    type: 'Private',
    ownership: 'Private',
    courses: ['Diploma'],
    specializations: ['CSE', 'ECE'],
    fees: { tuition: '30K - 50K' },
    placement: { percentage: 80, avgPackage: '2.5 LPA' },
    nirfRank: null,
    website: 'meipolytechnic.edu.in',
    sourceId: 'mei-poly'
  }
];
