export const realColleges = [
  // ENGINEERING
  {
    name: 'R.V. College of Engineering (RVCE)',
    sourceId: 'rvce-01',
    categories: ['Engineering'],
    type: 'Private',
    ownership: 'Private',
    district: 'Bengaluru (Bangalore) Urban',
    city: 'Bengaluru',
    universityAffiliation: 'Visvesvaraya Technological University (VTU)',
    establishedYear: 1963,
    courses: ['B.E / B.Tech', 'M.Tech', 'MCA'],
    specializations: ['Computer Science and Engineering', 'Information Science and Engineering', 'Electronics and Communication Engineering', 'Mechanical Engineering', 'Civil Engineering', 'Aerospace Engineering'],
    fees: { tuition: '₹10L - ₹12L', hostel: '₹1L' },
    placement: { highestPackage: '₹62 LPA', avgPackage: '₹14 LPA', percentage: 95 },
    entranceExams: ['KCET', 'COMEDK', 'JEE Main']
  },
  {
    name: 'PES University (PESU)',
    sourceId: 'pesu-01',
    categories: ['Engineering', 'Management', 'Science'],
    type: 'Private',
    ownership: 'Private',
    district: 'Bengaluru (Bangalore) Urban',
    city: 'Bengaluru',
    universityAffiliation: 'Private University',
    establishedYear: 1972,
    courses: ['B.E / B.Tech', 'BBA', 'MBA', 'B.Sc'],
    specializations: ['Computer Science and Engineering', 'Artificial Intelligence and Machine Learning', 'Electronics and Communication Engineering', 'Mechanical Engineering'],
    fees: { tuition: '₹14L - ₹16L', hostel: '₹1.5L' },
    placement: { highestPackage: '₹65 LPA', avgPackage: '₹15 LPA', percentage: 95 },
    entranceExams: ['PESSAT', 'KCET', 'JEE Main']
  },
  {
    name: 'BMS College of Engineering (BMSCE)',
    sourceId: 'bmsce-01',
    categories: ['Engineering', 'Management'],
    type: 'Private',
    ownership: 'Private Aided',
    district: 'Bengaluru (Bangalore) Urban',
    city: 'Bengaluru',
    universityAffiliation: 'Visvesvaraya Technological University (VTU)',
    establishedYear: 1946,
    courses: ['B.E / B.Tech', 'MBA', 'MCA'],
    specializations: ['Computer Science and Engineering', 'Information Science and Engineering', 'Electrical and Electronics Engineering', 'Mechanical Engineering', 'Civil Engineering'],
    fees: { tuition: '₹9L - ₹11L', hostel: '₹1L' },
    placement: { highestPackage: '₹50 LPA', avgPackage: '₹10 LPA', percentage: 90 },
    entranceExams: ['KCET', 'COMEDK', 'JEE Main']
  },
  {
    name: 'M. S. Ramaiah Institute of Technology (MSRIT)',
    sourceId: 'msrit-01',
    categories: ['Engineering', 'Management', 'Design'],
    type: 'Private',
    ownership: 'Private',
    district: 'Bengaluru (Bangalore) Urban',
    city: 'Bengaluru',
    universityAffiliation: 'Visvesvaraya Technological University (VTU)',
    establishedYear: 1962,
    courses: ['B.E / B.Tech', 'B.Arch', 'MBA', 'MCA'],
    specializations: ['Computer Science and Engineering', 'Information Science and Engineering', 'Medical Electronics Engineering', 'Civil Engineering'],
    fees: { tuition: '₹9L - ₹11L' },
    placement: { highestPackage: '₹50 LPA', avgPackage: '₹10 LPA', percentage: 92 },
    entranceExams: ['KCET', 'COMEDK', 'NATA']
  },
  {
    name: 'National Institute of Technology Karnataka (NITK)',
    sourceId: 'nitk-01',
    categories: ['Engineering', 'Science', 'Management'],
    type: 'Government',
    ownership: 'Government',
    district: 'Dakshina Kannada',
    city: 'Surathkal',
    universityAffiliation: 'Autonomous',
    establishedYear: 1960,
    courses: ['B.E / B.Tech', 'M.Tech', 'MBA', 'MCA', 'Ph.D'],
    specializations: ['Computer Science and Engineering', 'Information Technology', 'Mechanical Engineering', 'Civil Engineering', 'Chemical Engineering', 'Metallurgical and Materials Engineering'],
    fees: { tuition: '₹5L - ₹6L' },
    placement: { highestPackage: '₹54 LPA', avgPackage: '₹18 LPA', percentage: 98 },
    entranceExams: ['JEE Main', 'GATE']
  },
  {
    name: 'Manipal Institute of Technology (MIT)',
    sourceId: 'mit-01',
    categories: ['Engineering'],
    type: 'Private',
    ownership: 'Private',
    district: 'Udupi',
    city: 'Manipal',
    universityAffiliation: 'Manipal Academy of Higher Education (MAHE)',
    establishedYear: 1957,
    courses: ['B.E / B.Tech', 'M.Tech', 'MCA'],
    specializations: ['Computer Science and Engineering', 'Data Science', 'Mechatronics', 'Electronics and Communication Engineering', 'Aeronautical Engineering'],
    fees: { tuition: '₹16L - ₹18L', hostel: '₹1.5L' },
    placement: { highestPackage: '₹54 LPA', avgPackage: '₹12.5 LPA', percentage: 92 },
    entranceExams: ['MET']
  },
  {
    name: 'Sri Jayachamarajendra College of Engineering (SJCE)',
    sourceId: 'sjce-01',
    categories: ['Engineering', 'Management'],
    type: 'Private',
    ownership: 'Private Aided',
    district: 'Mysuru (Mysore)',
    city: 'Mysuru',
    universityAffiliation: 'JSS Science and Technology University',
    establishedYear: 1963,
    courses: ['B.E / B.Tech', 'M.Tech', 'MBA', 'MCA'],
    specializations: ['Computer Science and Engineering', 'Environmental Engineering', 'Polymer Science and Technology', 'Mechanical Engineering'],
    fees: { tuition: '₹7L - ₹9L' },
    placement: { highestPackage: '₹40 LPA', avgPackage: '₹9 LPA', percentage: 88 },
    entranceExams: ['KCET', 'COMEDK']
  },
  {
    name: 'SDM College of Engineering and Technology',
    sourceId: 'sdmcet-01',
    categories: ['Engineering'],
    type: 'Private',
    ownership: 'Private',
    district: 'Dharwad',
    city: 'Dharwad',
    universityAffiliation: 'Visvesvaraya Technological University (VTU)',
    establishedYear: 1979,
    courses: ['B.E / B.Tech', 'M.Tech'],
    specializations: ['Computer Science and Engineering', 'Information Science and Engineering', 'Electronics and Communication Engineering', 'Civil Engineering'],
    fees: { tuition: '₹6L - ₹8L' },
    placement: { highestPackage: '₹30 LPA', avgPackage: '₹6 LPA', percentage: 85 },
    entranceExams: ['KCET', 'COMEDK']
  },
  // MEDICAL
  {
    name: 'Bangalore Medical College and Research Institute (BMCRI)',
    sourceId: 'bmcri-02',
    categories: ['Medical', 'Paramedical'],
    type: 'Government',
    ownership: 'Government',
    district: 'Bengaluru (Bangalore) Urban',
    city: 'Bengaluru',
    universityAffiliation: 'Rajiv Gandhi University of Health Sciences (RGUHS)',
    establishedYear: 1955,
    courses: ['MBBS', 'MD', 'MS', 'B.Sc Nursing', 'Diploma in Medical Lab Technology'],
    specializations: ['Medicine and Surgery', 'Nursing', 'Medical Laboratory Technology', 'Radiology'],
    fees: { tuition: '₹3L' },
    placement: { percentage: 100 },
    entranceExams: ['NEET UG', 'NEET PG']
  },
  {
    name: 'Kasturba Medical College (KMC)',
    sourceId: 'kmc-01',
    categories: ['Medical'],
    type: 'Private',
    ownership: 'Private',
    district: 'Udupi',
    city: 'Manipal',
    universityAffiliation: 'Manipal Academy of Higher Education (MAHE)',
    establishedYear: 1953,
    courses: ['MBBS', 'MD', 'MS'],
    specializations: ['Medicine and Surgery'],
    fees: { tuition: '₹70L - ₹80L' },
    entranceExams: ['NEET UG', 'NEET PG']
  },
  {
    name: 'JSS Medical College',
    sourceId: 'jssmc-01',
    categories: ['Medical'],
    type: 'Private',
    ownership: 'Private',
    district: 'Mysuru (Mysore)',
    city: 'Mysuru',
    universityAffiliation: 'JSS Academy of Higher Education and Research',
    establishedYear: 1984,
    courses: ['MBBS', 'B.Sc Allied Health Sciences', 'MD', 'MS'],
    specializations: ['Medicine and Surgery', 'Anaesthesia Technology', 'Medical Laboratory Technology'],
    fees: { tuition: '₹60L - ₹75L' },
    entranceExams: ['NEET UG', 'NEET PG']
  },
  {
    name: 'Karnataka Institute of Medical Sciences (KIMS)',
    sourceId: 'kims-01',
    categories: ['Medical'],
    type: 'Government',
    ownership: 'Government',
    district: 'Dharwad',
    city: 'Hubballi',
    universityAffiliation: 'Rajiv Gandhi University of Health Sciences (RGUHS)',
    establishedYear: 1957,
    courses: ['MBBS', 'MD', 'MS', 'Nursing'],
    specializations: ['Medicine and Surgery'],
    fees: { tuition: '₹3L' },
    entranceExams: ['NEET UG']
  },
  {
    name: 'BGS Global Institute of Medical Sciences',
    sourceId: 'bgsgims-01',
    categories: ['Medical'],
    type: 'Private',
    ownership: 'Private',
    district: 'Bengaluru (Bangalore) Urban',
    city: 'Bengaluru',
    universityAffiliation: 'Rajiv Gandhi University of Health Sciences (RGUHS)',
    establishedYear: 2013,
    courses: ['MBBS', 'MD', 'MS'],
    specializations: ['Medicine and Surgery'],
    fees: { tuition: '₹40L - ₹50L' },
    entranceExams: ['NEET UG']
  },
  // LAW
  {
    name: 'National Law School of India University (NLSIU)',
    sourceId: 'nlsiu-01',
    categories: ['Law'],
    type: 'Government',
    ownership: 'Government',
    district: 'Bengaluru (Bangalore) Urban',
    city: 'Bengaluru',
    universityAffiliation: 'Autonomous',
    establishedYear: 1986,
    courses: ['BA LLB', 'LLM', 'Ph.D'],
    specializations: ['Law', 'Business Law', 'Human Rights Law'],
    fees: { tuition: '₹12L - ₹15L' },
    placement: { highestPackage: '₹20 LPA', avgPackage: '₹16 LPA', percentage: 100 },
    entranceExams: ['CLAT']
  },
  {
    name: 'Christ University - School of Law',
    sourceId: 'christ-law-01',
    categories: ['Law', 'Management', 'Science', 'Commerce', 'Design'],
    type: 'Private',
    ownership: 'Private',
    district: 'Bengaluru (Bangalore) Urban',
    city: 'Bengaluru',
    universityAffiliation: 'Christ University (Deemed to be University)',
    establishedYear: 2006,
    courses: ['BA LLB', 'BBA LLB', 'LLM'],
    specializations: ['Law', 'Corporate Law', 'Constitutional Law'],
    fees: { tuition: '₹8L - ₹10L' },
    placement: { avgPackage: '₹7 LPA', percentage: 85 },
    entranceExams: ['CULEE']
  },
  {
    name: 'JSS Law College',
    sourceId: 'jss-law-01',
    categories: ['Law'],
    type: 'Private',
    ownership: 'Private',
    district: 'Mysuru (Mysore)',
    city: 'Mysuru',
    universityAffiliation: 'Karnataka State Law University',
    establishedYear: 1982,
    courses: ['LLB', 'BA LLB', 'BBA LLB', 'LLM'],
    specializations: ['Law', 'Corporate Law'],
    entranceExams: ['KLEE', 'CLAT']
  },
  // MANAGEMENT / COMMERCE / DEGREE
  {
    name: 'Indian Institute of Management Bangalore (IIMB)',
    sourceId: 'iimb-01',
    categories: ['Management'],
    type: 'Government',
    ownership: 'Government',
    district: 'Bengaluru (Bangalore) Urban',
    city: 'Bengaluru',
    universityAffiliation: 'Autonomous',
    establishedYear: 1973,
    courses: ['PGDM', 'MBA', 'Ph.D'],
    specializations: ['Finance', 'Marketing', 'Operations', 'Strategy'],
    fees: { tuition: '₹24L' },
    placement: { highestPackage: '₹80 LPA', avgPackage: '₹35 LPA', percentage: 100 },
    entranceExams: ['CAT']
  },
  {
    name: 'St. Joseph\'s College of Commerce (SJCC)',
    sourceId: 'sjcc-01',
    categories: ['Commerce', 'Management'],
    type: 'Private',
    ownership: 'Private Aided',
    district: 'Bengaluru (Bangalore) Urban',
    city: 'Bengaluru',
    universityAffiliation: 'Bengaluru City University',
    establishedYear: 1972,
    courses: ['B.Com', 'BBA', 'M.Com'],
    specializations: ['Accounting', 'Finance', 'International Business', 'Analytics'],
    fees: { tuition: '₹3L - ₹5L' },
    placement: { highestPackage: '₹21 LPA', avgPackage: '₹6 LPA', percentage: 90 },
    entranceExams: ['College Entrance Test']
  },
  {
    name: 'Mount Carmel College (MCC)',
    sourceId: 'mcc-01',
    categories: ['Science', 'Commerce', 'Management', 'Design'],
    type: 'Private',
    ownership: 'Private Aided',
    district: 'Bengaluru (Bangalore) Urban',
    city: 'Bengaluru',
    universityAffiliation: 'Bengaluru City University',
    establishedYear: 1948,
    courses: ['B.Sc', 'B.Com', 'BBA', 'BA', 'M.Sc'],
    specializations: ['Biotechnology', 'Data Science', 'Finance', 'Psychology', 'Fashion Design'],
    fees: { tuition: '₹2L - ₹4L' },
    placement: { avgPackage: '₹5 LPA', percentage: 80 }
  },
  {
    name: 'Kristu Jayanti College',
    sourceId: 'kjc-01',
    categories: ['Commerce', 'Management', 'Science'],
    type: 'Private',
    ownership: 'Private',
    district: 'Bengaluru (Bangalore) Urban',
    city: 'Bengaluru',
    universityAffiliation: 'Bengaluru North University',
    establishedYear: 1999,
    courses: ['BBA', 'B.Com', 'BCA', 'B.Sc', 'MBA', 'MCA'],
    specializations: ['Aviation Management', 'Finance', 'Computer Science', 'Psychology', 'Microbiology'],
    fees: { tuition: '₹2L - ₹4L' }
  },
  {
    name: 'Yuvaraja\'s College',
    sourceId: 'yuvarajas-01',
    categories: ['Science', 'Management'],
    type: 'Government',
    ownership: 'Government',
    district: 'Mysuru (Mysore)',
    city: 'Mysuru',
    universityAffiliation: 'University of Mysore',
    establishedYear: 1928,
    courses: ['B.Sc', 'BBA', 'BCA', 'M.Sc'],
    specializations: ['Physics', 'Chemistry', 'Mathematics', 'Botany', 'Zoology', 'Food Science and Nutrition']
  },
  // DIPLOMA / POLYTECHNIC / ITI
  {
    name: 'MEI Polytechnic',
    sourceId: 'mei-poly-01',
    categories: ['Polytechnic', 'Diploma', 'Engineering'],
    type: 'Private',
    ownership: 'Private Aided',
    district: 'Bengaluru (Bangalore) Urban',
    city: 'Bengaluru',
    universityAffiliation: 'Department of Technical Education (DTE)',
    establishedYear: 1962,
    courses: ['Diploma in Engineering'],
    specializations: ['Diploma CSE', 'Diploma Mechanical', 'Diploma Civil', 'Diploma ECE', 'Diploma Electrical'],
    fees: { tuition: '₹30K - ₹60K' }
  },
  {
    name: 'Government Polytechnic, Mysuru',
    sourceId: 'gov-poly-mysuru',
    categories: ['Polytechnic', 'Diploma'],
    type: 'Government',
    ownership: 'Government',
    district: 'Mysuru (Mysore)',
    city: 'Mysuru',
    universityAffiliation: 'Department of Technical Education (DTE)',
    establishedYear: 1954,
    courses: ['Diploma in Engineering'],
    specializations: ['Diploma Civil', 'Diploma Mechanical', 'Diploma ECE'],
    fees: { tuition: '₹15K' }
  },
  {
    name: 'Government Industrial Training Institute (ITI), Hosur Road',
    sourceId: 'gov-iti-hosur',
    categories: ['ITI', 'Vocational'],
    type: 'Government',
    ownership: 'Government',
    district: 'Bengaluru (Bangalore) Urban',
    city: 'Bengaluru',
    universityAffiliation: 'NCVT',
    establishedYear: 1960,
    courses: ['ITI Trades'],
    specializations: ['Electrician', 'Fitter', 'Turner', 'Welder', 'COPA', 'Draughtsman'],
    fees: { tuition: '₹5K' }
  },
  {
    name: 'JSS Industrial Training Institute',
    sourceId: 'jss-iti-01',
    categories: ['ITI', 'Vocational'],
    type: 'Private',
    ownership: 'Private',
    district: 'Mysuru (Mysore)',
    city: 'Mysuru',
    universityAffiliation: 'NCVT',
    courses: ['ITI Trades'],
    specializations: ['Electrician', 'Fitter', 'Electronics Mechanic'],
    fees: { tuition: '₹20K' }
  },
  // DESIGN & PARAMEDICAL
  {
    name: 'National Institute of Design (NID) Bengaluru',
    sourceId: 'nid-blr-01',
    categories: ['Design'],
    type: 'Government',
    ownership: 'Government',
    district: 'Bengaluru (Bangalore) Urban',
    city: 'Bengaluru',
    universityAffiliation: 'Autonomous',
    establishedYear: 2006,
    courses: ['M.Des'],
    specializations: ['Information Design', 'Interaction Design', 'Universal Design'],
    fees: { tuition: '₹8L' },
    entranceExams: ['NID DAT']
  },
  {
    name: 'Srishti Manipal Institute of Art, Design and Technology',
    sourceId: 'srishti-01',
    categories: ['Design'],
    type: 'Private',
    ownership: 'Private',
    district: 'Bengaluru (Bangalore) Urban',
    city: 'Bengaluru',
    universityAffiliation: 'Manipal Academy of Higher Education (MAHE)',
    establishedYear: 1996,
    courses: ['B.Des', 'M.Des', 'B.Voc'],
    specializations: ['Graphic Design', 'Industrial Design', 'Animation', 'UX/UI Design'],
    fees: { tuition: '₹15L - ₹20L' },
    entranceExams: ['SMEAT']
  },
  {
    name: 'Sanjay Gandhi Institute of Trauma and Orthopaedics',
    sourceId: 'sgito-01',
    categories: ['Medical', 'Paramedical'],
    type: 'Government',
    ownership: 'Government',
    district: 'Bengaluru (Bangalore) Urban',
    city: 'Bengaluru',
    universityAffiliation: 'Rajiv Gandhi University of Health Sciences (RGUHS)',
    courses: ['B.Sc Allied Health Sciences', 'Diploma in Paramedical'],
    specializations: ['Operation Theatre Technology', 'Radiology', 'Medical Laboratory Technology', 'Physiotherapy']
  }
];
