import mongoose from 'mongoose';
import dotenv from 'dotenv';
import College from '../src/models/College.js';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
dotenv.config({ path: path.join(__dirname, '../.env') });

const karnatakaColleges = [
  // ----------------------------------------------------
  // MULTI-DISCIPLINARY / ENGINEERING / MANAGEMENT / SCIENCE
  // ----------------------------------------------------
  {
    name: 'Indian Institute of Science (IISc)',
    categories: ['Engineering', 'Science', 'Management'],
    type: 'Government',
    institutionType: 'Deemed University',
    ownership: 'Government',
    state: 'Karnataka',
    district: 'Bengaluru Urban',
    city: 'Bengaluru',
    address: 'CV Raman Rd, Bengaluru, Karnataka 560012',
    universityAffiliation: 'Autonomous',
    approvalBody: 'UGC',
    establishedYear: 1909,
    courses: ['B.Tech', 'M.Tech', 'Ph.D', 'B.Sc (Research)'],
    programs: ['Computer Science', 'Aerospace Engineering', 'Physics', 'Management Studies'],
    specializations: ['Artificial Intelligence', 'Quantum Physics', 'Materials Science'],
    description: 'Premier institute for advanced scientific and technological research and education in India.',
    facilities: ['Supercomputer', 'Library', 'Hostel', 'Sports Complex', 'Labs'],
    admissionProcess: 'Through JEE Advanced / KVPY / GATE / CAT',
    entranceExams: ['JEE Advanced', 'GATE', 'CAT'],
    eligibility: '10+2 with 75% for UG, Relevant Degree for PG',
    fees: {
      tuition: '₹30,000/yr',
      hostel: '₹15,000/yr',
      other: '₹5,000/yr'
    },
    hostelAvailable: true,
    scholarshipsAvailable: true,
    placement: {
      percentage: 95,
      highestPackage: '₹85 LPA',
      avgPackage: '₹28 LPA',
      topRecruiters: ['Google', 'Microsoft', 'Amazon', 'ISRO']
    },
    accreditation: 'NAAC A++',
    nirfRank: 1,
    website: 'https://iisc.ac.in',
    phone: '080-22932004',
    email: 'admissions@iisc.ac.in',
    latitude: 13.0198,
    longitude: 77.5660,
    image: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800&q=80',
    logo: 'https://iisc.ac.in/wp-content/uploads/2020/08/IISc_Master_Seal_Black_Transparent.png',
    sourceName: 'NIRF / AISHE',
    sourceUrl: 'https://www.nirfindia.org/',
    verifiedAt: new Date(),
    isVerified: true
  },
  {
    name: 'National Institute of Technology Karnataka (NITK)',
    categories: ['Engineering', 'Management', 'Science'],
    type: 'Government',
    institutionType: 'Institute of National Importance',
    ownership: 'Government',
    state: 'Karnataka',
    district: 'Dakshina Kannada',
    city: 'Surathkal',
    address: 'NH 66, Srinivasnagar, Surathkal, Mangaluru, Karnataka 575025',
    universityAffiliation: 'Autonomous',
    approvalBody: 'AICTE',
    establishedYear: 1960,
    courses: ['B.Tech', 'M.Tech', 'MBA', 'MCA', 'Ph.D'],
    programs: ['Mechanical', 'Computer Science', 'Civil', 'Information Technology'],
    specializations: ['Data Science', 'VLSI Design', 'Structural Engineering'],
    description: 'One of the premier engineering institutes in India, located on the shores of the Arabian Sea.',
    facilities: ['Private Beach', 'Central Library', 'Hostel', 'Sports Complex', 'Incubation Centre'],
    admissionProcess: 'Through JEE Main / GATE / NIMCET / CAT',
    entranceExams: ['JEE Main', 'GATE', 'CAT', 'NIMCET'],
    eligibility: '10+2 with 75% for UG, Relevant Degree for PG',
    fees: {
      tuition: '₹1.4 Lakhs/yr',
      hostel: '₹35,000/yr',
      other: '₹15,000/yr'
    },
    hostelAvailable: true,
    scholarshipsAvailable: true,
    placement: {
      percentage: 92,
      highestPackage: '₹54 LPA',
      avgPackage: '₹18 LPA',
      topRecruiters: ['Microsoft', 'Amazon', 'Goldman Sachs', 'Uber']
    },
    accreditation: 'NAAC A+',
    nirfRank: 12,
    website: 'https://nitk.ac.in',
    phone: '0824-2474000',
    email: 'registrar@nitk.ac.in',
    latitude: 13.0108,
    longitude: 74.7943,
    image: 'https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80',
    logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/c/cc/NITK_Surathkal_Logo.svg/1200px-NITK_Surathkal_Logo.svg.png',
    sourceName: 'NIRF / AISHE',
    sourceUrl: 'https://www.nirfindia.org/',
    verifiedAt: new Date(),
    isVerified: true
  },
  {
    name: 'PES University',
    categories: ['Engineering', 'Management', 'Law', 'Commerce', 'Science', 'Design'],
    type: 'Private',
    institutionType: 'State Private University',
    ownership: 'Private',
    state: 'Karnataka',
    district: 'Bengaluru Urban',
    city: 'Bengaluru',
    address: '100 Feet Ring Road, BSK III Stage, Bengaluru, Karnataka 560085',
    universityAffiliation: 'Autonomous',
    approvalBody: 'UGC',
    establishedYear: 1972,
    courses: ['B.Tech', 'MBA', 'BBA', 'B.Com', 'B.Des', 'B.Sc', 'BA LLB'],
    programs: ['Computer Science', 'Electronics', 'Business Analytics', 'Graphic Design'],
    specializations: ['Machine Learning', 'Finance', 'Cybersecurity', 'Corporate Law'],
    description: 'PES University is a leading teaching and research institution in Bengaluru.',
    facilities: ['Library', 'Hostel', 'Sports Complex', 'Labs', 'Cafeteria', 'Hospital'],
    admissionProcess: 'Through PESSAT / KCET / COMEDK / CLAT',
    entranceExams: ['PESSAT', 'KCET', 'COMEDK', 'CLAT'],
    eligibility: '10+2 with 45%-60% depending on course',
    fees: {
      tuition: '₹4.5 Lakhs/yr',
      hostel: '₹1.1 Lakhs/yr',
      other: '₹20,000/yr'
    },
    hostelAvailable: true,
    scholarshipsAvailable: true,
    placement: {
      percentage: 88,
      highestPackage: '₹65 LPA',
      avgPackage: '₹12 LPA',
      topRecruiters: ['Atlassian', 'Akamai', 'Cisco', 'Palo Alto']
    },
    accreditation: 'NAAC A',
    nirfRank: 101,
    website: 'https://pes.edu',
    phone: '080-26721983',
    email: 'admissions@pes.edu',
    latitude: 12.9350,
    longitude: 77.5348,
    image: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800&q=80',
    logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/e/e4/PES_University_logo.svg/1200px-PES_University_logo.svg.png',
    sourceName: 'AISHE',
    sourceUrl: 'https://dashboard.aishe.gov.in/',
    verifiedAt: new Date(),
    isVerified: true
  },

  // ----------------------------------------------------
  // MEDICAL / PARAMEDICAL / PHARMACY
  // ----------------------------------------------------
  {
    name: 'Bangalore Medical College and Research Institute (BMCRI)',
    categories: ['Medical', 'Paramedical', 'Diploma'],
    type: 'Government',
    institutionType: 'Affiliated College',
    ownership: 'Government',
    state: 'Karnataka',
    district: 'Bengaluru Urban',
    city: 'Bengaluru',
    address: 'Fort, K.R. Road, Bengaluru, Karnataka 560002',
    universityAffiliation: 'RGUHS',
    approvalBody: 'NMC',
    establishedYear: 1955,
    courses: ['MBBS', 'MD', 'MS', 'B.Sc Nursing', 'Paramedical Diploma'],
    programs: ['General Medicine', 'Surgery', 'Anatomy', 'Radiology'],
    specializations: ['Cardiology', 'Neurology', 'Medical Lab Technology'],
    description: 'Premier government medical college in Karnataka with attached tertiary care hospitals.',
    facilities: ['Hospital', 'Library', 'Hostel', 'Auditorium', 'Blood Bank'],
    admissionProcess: 'Through NEET UG / NEET PG',
    entranceExams: ['NEET', 'NEET PG'],
    eligibility: '10+2 with PCB (50%) for UG',
    fees: {
      tuition: '₹70,000/yr',
      hostel: '₹20,000/yr',
      other: '₹5,000/yr'
    },
    hostelAvailable: true,
    scholarshipsAvailable: true,
    placement: {
      percentage: 100,
      highestPackage: 'N/A',
      avgPackage: 'N/A',
      topRecruiters: ['Government Hospitals', 'Apollo', 'Fortis']
    },
    accreditation: 'NMC Approved',
    nirfRank: 14,
    website: 'http://bmcri.karnataka.gov.in',
    phone: '080-26700810',
    email: 'director_bmcri@yahoo.co.in',
    latitude: 12.9587,
    longitude: 77.5739,
    image: 'https://images.unsplash.com/photo-1581056771107-24ca5f033842?w=800&q=80',
    logo: 'https://upload.wikimedia.org/wikipedia/en/6/65/Bangalore_Medical_College_and_Research_Institute_Logo.png',
    sourceName: 'NMC / AISHE',
    sourceUrl: 'https://www.nmc.org.in/',
    verifiedAt: new Date(),
    isVerified: true
  },
  {
    name: 'JSS College of Pharmacy',
    categories: ['Medical', 'Paramedical', 'Science', 'Diploma'],
    type: 'Private',
    institutionType: 'Constituent College',
    ownership: 'Deemed',
    state: 'Karnataka',
    district: 'Mysuru',
    city: 'Mysuru',
    address: 'Sri Shivarathreeshwara Nagara, Mysuru, Karnataka 570015',
    universityAffiliation: 'JSS Academy of Higher Education & Research',
    approvalBody: 'PCI',
    establishedYear: 1973,
    courses: ['B.Pharm', 'M.Pharm', 'Pharm.D', 'D.Pharm'],
    programs: ['Pharmacy Practice', 'Pharmaceutics', 'Pharmacology'],
    specializations: ['Clinical Pharmacy', 'Regulatory Affairs'],
    description: 'Ranked among the top pharmacy colleges in India, offering world-class research facilities.',
    facilities: ['Labs', 'Library', 'Hostel', 'Animal House', 'Clinical Setup'],
    admissionProcess: 'Through JSS JSSU PGET / KCET',
    entranceExams: ['KCET', 'JSS Entrance'],
    eligibility: '10+2 with PCM/PCB',
    fees: {
      tuition: '₹1.8 Lakhs/yr',
      hostel: '₹80,000/yr',
      other: '₹10,000/yr'
    },
    hostelAvailable: true,
    scholarshipsAvailable: true,
    placement: {
      percentage: 95,
      highestPackage: '₹12 LPA',
      avgPackage: '₹5 LPA',
      topRecruiters: ['Cipla', 'Sun Pharma', 'Novo Nordisk', 'IQVIA']
    },
    accreditation: 'NAAC A+',
    nirfRank: 7,
    website: 'https://jssuni.edu.in',
    phone: '0821-2548353',
    email: 'jsscpmy@jssuni.edu.in',
    latitude: 12.3375,
    longitude: 76.6433,
    image: 'https://images.unsplash.com/photo-1576086213369-97a306d36557?w=800&q=80',
    logo: 'https://jssuni.edu.in/assets/images/logo.png',
    sourceName: 'NIRF / PCI',
    sourceUrl: 'https://www.pci.nic.in/',
    verifiedAt: new Date(),
    isVerified: true
  },
  {
    name: 'Sanjay Gandhi Institute of Trauma and Orthopaedics',
    categories: ['Medical', 'Paramedical', 'Diploma'],
    type: 'Government',
    institutionType: 'Affiliated College',
    ownership: 'Government',
    state: 'Karnataka',
    district: 'Bengaluru Urban',
    city: 'Bengaluru',
    address: 'Byrasandra, Jayanagar East, Bengaluru, Karnataka 560011',
    universityAffiliation: 'RGUHS',
    approvalBody: 'Paramedical Board Karnataka',
    establishedYear: 1984,
    courses: ['B.Sc', 'Diploma'],
    programs: ['Allied Health Sciences', 'Paramedical Courses'],
    specializations: ['Operation Theatre Technology', 'X-Ray Technology', 'Medical Lab Technology'],
    description: 'Renowned government institute specializing in trauma care, orthopaedics, and allied health sciences training.',
    facilities: ['Hospital attached', 'Labs', 'Library', 'Hostel'],
    admissionProcess: 'Through PMB Karnataka Counselling',
    entranceExams: ['State PMB Exam'],
    eligibility: '10th for Diploma, 10+2 Science for B.Sc',
    fees: {
      tuition: '₹15,000/yr',
      hostel: '₹20,000/yr',
      other: '₹2,000/yr'
    },
    hostelAvailable: true,
    scholarshipsAvailable: true,
    placement: {
      percentage: 100,
      highestPackage: '₹4 LPA',
      avgPackage: '₹2.5 LPA',
      topRecruiters: ['Apollo Hospitals', 'Manipal Hospitals', 'Govt Hospitals']
    },
    accreditation: 'State PMB',
    website: 'http://sgito.karnataka.gov.in/',
    phone: '080-26564516',
    email: 'sgito@karnataka.gov.in',
    latitude: 12.9352,
    longitude: 77.5936,
    image: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=800&q=80',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/e/ea/SGITO_Logo.png',
    sourceName: 'Paramedical Board Karnataka',
    sourceUrl: 'http://www.pmbkarnataka.org/',
    verifiedAt: new Date(),
    isVerified: true
  },

  // ----------------------------------------------------
  // MANAGEMENT / COMMERCE
  // ----------------------------------------------------
  {
    name: 'Indian Institute of Management Bangalore (IIMB)',
    categories: ['Management'],
    type: 'Government',
    institutionType: 'Institute of National Importance',
    ownership: 'Government',
    state: 'Karnataka',
    district: 'Bengaluru Urban',
    city: 'Bengaluru',
    address: 'Bannerghatta Road, Bengaluru, Karnataka 560076',
    universityAffiliation: 'Autonomous',
    approvalBody: 'UGC',
    establishedYear: 1973,
    courses: ['MBA (PGP)', 'Ph.D', 'Executive MBA'],
    programs: ['Business Administration', 'Public Policy', 'Business Analytics'],
    specializations: ['Finance', 'Marketing', 'Strategy', 'Operations'],
    description: 'Top-ranked management institute in India known for its rigorous academic programs and global alumni network.',
    facilities: ['Library', 'Hostel', 'Sports Complex', 'Incubation Centre', 'Auditorium'],
    admissionProcess: 'Through CAT / GMAT',
    entranceExams: ['CAT', 'GMAT'],
    eligibility: 'Bachelor’s Degree with 50%',
    fees: {
      tuition: '₹24.5 Lakhs (Total)',
      hostel: 'Included',
      other: 'Included'
    },
    hostelAvailable: true,
    scholarshipsAvailable: true,
    placement: {
      percentage: 100,
      highestPackage: '₹1.15 Cr PA',
      avgPackage: '₹35.3 LPA',
      topRecruiters: ['McKinsey', 'BCG', 'Bain', 'Goldman Sachs']
    },
    accreditation: 'EQUIS, AMBA',
    nirfRank: 2,
    website: 'https://iimb.ac.in',
    phone: '080-26993000',
    email: 'pgpadm@iimb.ac.in',
    latitude: 12.8959,
    longitude: 77.6016,
    image: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=800&q=80',
    logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/e/e1/IIM_Bangalore_Logo.svg/1200px-IIM_Bangalore_Logo.svg.png',
    sourceName: 'NIRF',
    sourceUrl: 'https://www.nirfindia.org/',
    verifiedAt: new Date(),
    isVerified: true
  },
  {
    name: 'Christ University',
    categories: ['Management', 'Commerce', 'Science', 'Law', 'Design'],
    type: 'Private',
    institutionType: 'Deemed to be University',
    ownership: 'Private',
    state: 'Karnataka',
    district: 'Bengaluru Urban',
    city: 'Bengaluru',
    address: 'Hosur Road, Bhavani Nagar, Bengaluru, Karnataka 560029',
    universityAffiliation: 'Autonomous',
    approvalBody: 'UGC',
    establishedYear: 1969,
    courses: ['BBA', 'B.Com', 'MBA', 'BA LLB', 'B.Sc', 'M.Sc'],
    programs: ['Business Administration', 'Commerce', 'Psychology', 'Computer Applications'],
    specializations: ['Finance', 'Human Resources', 'Clinical Psychology'],
    description: 'Renowned for its commerce, management, and arts programs with a vibrant multi-disciplinary campus.',
    facilities: ['Library', 'Hostels', 'Sports Complex', 'Auditoriums', 'Chapel'],
    admissionProcess: 'CUET (Christ University Entrance Test) + Interview',
    entranceExams: ['CUET', 'MAT', 'CAT'],
    eligibility: '10+2 with minimum 50% / Degree for PG',
    fees: {
      tuition: '₹1.5 Lakhs/yr (BBA)',
      hostel: '₹60,000/yr',
      other: '₹15,000/yr'
    },
    hostelAvailable: true,
    scholarshipsAvailable: true,
    placement: {
      percentage: 85,
      highestPackage: '₹20 LPA',
      avgPackage: '₹7 LPA',
      topRecruiters: ['Deloitte', 'KPMG', 'EY', 'Amazon']
    },
    accreditation: 'NAAC A',
    nirfRank: 60,
    website: 'https://christuniversity.in',
    phone: '080-40129100',
    email: 'mail@christuniversity.in',
    latitude: 12.9344,
    longitude: 77.6059,
    image: 'https://images.unsplash.com/photo-1541829070764-84a7d30dd3f3?w=800&q=80',
    logo: 'https://christuniversity.in/images/logo.jpg',
    sourceName: 'AISHE',
    sourceUrl: 'https://dashboard.aishe.gov.in/',
    verifiedAt: new Date(),
    isVerified: true
  },
  {
    name: 'St. Joseph\'s College of Commerce (SJCC)',
    categories: ['Commerce', 'Management'],
    type: 'Private',
    institutionType: 'Autonomous College',
    ownership: 'Private',
    state: 'Karnataka',
    district: 'Bengaluru Urban',
    city: 'Bengaluru',
    address: '163, Brigade Road, Bengaluru, Karnataka 560025',
    universityAffiliation: 'Bengaluru City University',
    approvalBody: 'UGC',
    establishedYear: 1972,
    courses: ['B.Com', 'BBA', 'M.Com', 'PG Diploma'],
    programs: ['Commerce', 'Business Administration'],
    specializations: ['Travel & Tourism', 'International Accounting', 'Analytics'],
    description: 'One of the oldest and most prestigious commerce colleges in India.',
    facilities: ['Library', 'Computer Labs', 'Sports Ground', 'Cafeteria'],
    admissionProcess: 'Aptitude Test + Interview',
    entranceExams: ['SJCC Entrance Test'],
    eligibility: '10+2 with minimum 60%',
    fees: {
      tuition: '₹1.2 Lakhs/yr',
      hostel: '₹85,000/yr',
      other: '₹10,000/yr'
    },
    hostelAvailable: true,
    scholarshipsAvailable: true,
    placement: {
      percentage: 90,
      highestPackage: '₹14 LPA',
      avgPackage: '₹5.5 LPA',
      topRecruiters: ['Goldman Sachs', 'Deloitte', 'KPMG', 'Target']
    },
    accreditation: 'NAAC A++',
    nirfRank: 65,
    website: 'https://www.sjcc.edu.in',
    phone: '080-25360644',
    email: 'info@sjcc.edu.in',
    latitude: 12.9719,
    longitude: 77.6083,
    image: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=800&q=80',
    logo: 'https://www.sjcc.edu.in/images/logo.png',
    sourceName: 'UGC',
    sourceUrl: 'https://www.ugc.gov.in/',
    verifiedAt: new Date(),
    isVerified: true
  },

  // ----------------------------------------------------
  // LAW
  // ----------------------------------------------------
  {
    name: 'National Law School of India University (NLSIU)',
    categories: ['Law'],
    type: 'Government',
    institutionType: 'State University',
    ownership: 'Government',
    state: 'Karnataka',
    district: 'Bengaluru Urban',
    city: 'Bengaluru',
    address: 'Gnana Bharathi Main Rd, Teachers Colony, Naagarabhaavi, Bengaluru, Karnataka 560072',
    universityAffiliation: 'Autonomous',
    approvalBody: 'BCI',
    establishedYear: 1986,
    courses: ['BA LLB (Hons)', 'LLM', 'Ph.D'],
    programs: ['Undergraduate Law', 'Postgraduate Law'],
    specializations: ['Business Law', 'Human Rights', 'Public Policy'],
    description: 'India’s premier law university, consistently ranked #1 in the country.',
    facilities: ['Narayan Rao Melgiri Memorial National Law Library', 'Hostels', 'Sports Complex', 'Moot Court'],
    admissionProcess: 'Through CLAT (Common Law Admission Test)',
    entranceExams: ['CLAT'],
    eligibility: '10+2 with minimum 45%',
    fees: {
      tuition: '₹3.2 Lakhs/yr',
      hostel: '₹50,000/yr',
      other: '₹25,000/yr'
    },
    hostelAvailable: true,
    scholarshipsAvailable: true,
    placement: {
      percentage: 100,
      highestPackage: '₹16 LPA (Domestic)',
      avgPackage: '₹14 LPA',
      topRecruiters: ['Cyril Amarchand Mangaldas', 'Khaitan & Co', 'Trilegal']
    },
    accreditation: 'BCI Approved',
    nirfRank: 1,
    website: 'https://www.nls.ac.in',
    phone: '080-23160532',
    email: 'contactus@nls.ac.in',
    latitude: 12.9667,
    longitude: 77.5100,
    image: 'https://images.unsplash.com/photo-1589829085413-56de8ae18c73?w=800&q=80',
    logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/d/d3/National_Law_School_of_India_University_logo.svg/1200px-National_Law_School_of_India_University_logo.svg.png',
    sourceName: 'NIRF / BCI',
    sourceUrl: 'https://www.nirfindia.org/',
    verifiedAt: new Date(),
    isVerified: true
  },

  // ----------------------------------------------------
  // DESIGN
  // ----------------------------------------------------
  {
    name: 'National Institute of Fashion Technology (NIFT) Bengaluru',
    categories: ['Design', 'Vocational'],
    type: 'Government',
    institutionType: 'Institute of National Importance',
    ownership: 'Government',
    state: 'Karnataka',
    district: 'Bengaluru Urban',
    city: 'Bengaluru',
    address: 'No. 21st, 16th Cross Rd, Sector 1, HSR Layout, Bengaluru, Karnataka 560102',
    universityAffiliation: 'Autonomous',
    approvalBody: 'Ministry of Textiles',
    establishedYear: 1997,
    courses: ['B.Des', 'B.FTech', 'M.Des', 'M.F.M'],
    programs: ['Fashion Design', 'Textile Design', 'Accessory Design', 'Fashion Communication'],
    specializations: ['Knitwear Design', 'Fashion Management'],
    description: 'Premier institute for fashion education, design, and management in India.',
    facilities: ['Design Studios', 'Resource Centre', 'Hostels', 'Garment Construction Labs'],
    admissionProcess: 'NIFT Entrance Exam',
    entranceExams: ['NIFT GAT/CAT'],
    eligibility: '10+2 from any recognized board',
    fees: {
      tuition: '₹2.8 Lakhs/yr',
      hostel: '₹60,000/yr',
      other: '₹20,000/yr'
    },
    hostelAvailable: true,
    scholarshipsAvailable: true,
    placement: {
      percentage: 90,
      highestPackage: '₹18 LPA',
      avgPackage: '₹7 LPA',
      topRecruiters: ['Arvind', 'Myntra', 'Lifestyle', 'Gaurav Gupta']
    },
    accreditation: 'Ministry of Textiles',
    nirfRank: 15,
    website: 'https://nift.ac.in/bengaluru',
    phone: '080-22552550',
    email: 'director.bengaluru@nift.ac.in',
    latitude: 12.9103,
    longitude: 77.6450,
    image: 'https://images.unsplash.com/photo-1558769132-cb1fac08b4af?w=800&q=80',
    logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/e/e0/National_Institute_of_Fashion_Technology_logo.svg/1200px-National_Institute_of_Fashion_Technology_logo.svg.png',
    sourceName: 'AISHE',
    sourceUrl: 'https://dashboard.aishe.gov.in/',
    verifiedAt: new Date(),
    isVerified: true
  },
  {
    name: 'Srishti Manipal Institute of Art, Design and Technology',
    categories: ['Design', 'Vocational'],
    type: 'Private',
    institutionType: 'Constituent College',
    ownership: 'Private',
    state: 'Karnataka',
    district: 'Bengaluru Urban',
    city: 'Bengaluru',
    address: 'N3 Campus, Yelahanka, Bengaluru, Karnataka 560064',
    universityAffiliation: 'Manipal Academy of Higher Education (MAHE)',
    approvalBody: 'UGC',
    establishedYear: 1996,
    courses: ['B.Des', 'B.Voc', 'M.Des', 'M.Plan'],
    programs: ['Visual Communication', 'Industrial Design', 'Animation', 'Film'],
    specializations: ['Human Centered Design', 'Digital Media Arts'],
    description: 'Renowned for its progressive, multi-disciplinary approach to art and design education.',
    facilities: ['Studios', 'Media Labs', 'Library', 'Workshops'],
    admissionProcess: 'Srishti Manipal Entrance & Aptitude Test (SMEAT)',
    entranceExams: ['SMEAT'],
    eligibility: '10+2 or equivalent',
    fees: {
      tuition: '₹6.5 Lakhs/yr',
      hostel: '₹1.5 Lakhs/yr',
      other: '₹25,000/yr'
    },
    hostelAvailable: true,
    scholarshipsAvailable: true,
    placement: {
      percentage: 85,
      highestPackage: '₹15 LPA',
      avgPackage: '₹6.5 LPA',
      topRecruiters: ['IDEO', 'Frog Design', 'Amazon', 'Tata Elxsi']
    },
    accreditation: 'NAAC A++',
    website: 'https://srishtimanipalinstitute.in',
    phone: '080-49000800',
    email: 'admissions@srishti.ac.in',
    latitude: 13.1155,
    longitude: 77.5891,
    image: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=800&q=80',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/e/e4/MAHE_Logo.png',
    sourceName: 'MAHE',
    sourceUrl: 'https://manipal.edu/',
    verifiedAt: new Date(),
    isVerified: true
  },

  // ----------------------------------------------------
  // DIPLOMA / POLYTECHNIC / ITI / VOCATIONAL
  // ----------------------------------------------------
  {
    name: 'Government Tool Room & Training Centre (GTTC) Mysuru',
    categories: ['Diploma', 'Polytechnic', 'ITI', 'Engineering', 'Vocational'],
    type: 'Government',
    institutionType: 'Training Centre / Polytechnic',
    ownership: 'Government',
    state: 'Karnataka',
    district: 'Mysuru',
    city: 'Mysuru',
    address: 'Belagola Industrial Area, Metagalli, Mysuru, Karnataka 570016',
    universityAffiliation: 'Directorate of Technical Education (DTE)',
    approvalBody: 'AICTE',
    establishedYear: 1992,
    courses: ['Diploma', 'Certificate Courses', 'Short-term Vocational'],
    programs: ['Tool & Die Making', 'Precision Manufacturing', 'Mechatronics'],
    specializations: ['CNC Programming', 'CAD/CAM', 'Automation'],
    description: 'Premier government institute for high-end skill development, tool design, and manufacturing.',
    facilities: ['Advanced CNC Labs', 'Tool Room', 'Library', 'Hostel'],
    admissionProcess: 'Merit-based + State Diploma Counselling',
    entranceExams: ['None'],
    eligibility: '10th Pass (SSLC)',
    fees: {
      tuition: '₹12,000/yr',
      hostel: '₹15,000/yr',
      other: '₹3,000/yr'
    },
    hostelAvailable: true,
    scholarshipsAvailable: true,
    placement: {
      percentage: 100,
      highestPackage: '₹5 LPA',
      avgPackage: '₹2.5 LPA',
      topRecruiters: ['Toyota', 'Bosch', 'HAL', 'BEML']
    },
    accreditation: 'ISO Certified, AICTE',
    website: 'https://gttc.karnataka.gov.in',
    phone: '0821-2581290',
    email: 'gttcmysore@yahoo.co.in',
    latitude: 12.3570,
    longitude: 76.6210,
    image: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800&q=80',
    logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/e/eb/GTTC_Logo.png/220px-GTTC_Logo.png',
    sourceName: 'AICTE / DTE Karnataka',
    sourceUrl: 'https://dtetech.karnataka.gov.in/',
    verifiedAt: new Date(),
    isVerified: true
  },
  {
    name: 'Government Polytechnic, Bengaluru',
    categories: ['Diploma', 'Polytechnic'],
    type: 'Government',
    institutionType: 'Polytechnic',
    ownership: 'Government',
    state: 'Karnataka',
    district: 'Bengaluru Urban',
    city: 'Bengaluru',
    address: 'Seshadri Rd, Ambedkar Veedhi, Bengaluru, Karnataka 560001',
    universityAffiliation: 'Directorate of Technical Education (DTE)',
    approvalBody: 'AICTE',
    establishedYear: 1943,
    courses: ['Diploma'],
    programs: ['Civil', 'Mechanical', 'Electrical', 'Electronics', 'Computer Science'],
    specializations: ['Automobile', 'Architecture'],
    description: 'One of the oldest and most reputed government polytechnic colleges in Karnataka.',
    facilities: ['Workshops', 'Library', 'Hostel', 'Playground'],
    admissionProcess: 'Centralised DTE Counselling',
    entranceExams: ['None'],
    eligibility: '10th Pass (SSLC)',
    fees: {
      tuition: '₹4,500/yr',
      hostel: '₹10,000/yr',
      other: '₹1,000/yr'
    },
    hostelAvailable: true,
    scholarshipsAvailable: true,
    placement: {
      percentage: 80,
      highestPackage: '₹4 LPA',
      avgPackage: '₹2 LPA',
      topRecruiters: ['L&T', 'TVS', 'Volvo', 'Infosys']
    },
    accreditation: 'AICTE',
    website: 'http://gptbangalore.ac.in/',
    phone: '080-22262931',
    email: 'principalgptb@gmail.com',
    latitude: 12.9772,
    longitude: 77.5855,
    image: 'https://images.unsplash.com/photo-1574607407408-1e681c46041d?w=800&q=80',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Government_of_Karnataka_Logo.png/200px-Government_of_Karnataka_Logo.png',
    sourceName: 'DTE Karnataka',
    sourceUrl: 'https://dtetech.karnataka.gov.in/',
    verifiedAt: new Date(),
    isVerified: true
  },
  {
    name: 'Government ITI, Peenya',
    categories: ['ITI', 'Vocational'],
    type: 'Government',
    institutionType: 'Industrial Training Institute',
    ownership: 'Government',
    state: 'Karnataka',
    district: 'Bengaluru Urban',
    city: 'Bengaluru',
    address: 'Peenya Industrial Area Phase IV, Bengaluru, Karnataka 560058',
    universityAffiliation: 'NCVT (National Council for Vocational Training)',
    approvalBody: 'DGT, Ministry of Skill Development',
    establishedYear: 1980,
    courses: ['ITI Trades'],
    programs: ['Fitter', 'Electrician', 'Welder', 'Turner', 'Machinist'],
    specializations: ['Automobile Mechanic', 'Electronics Mechanic'],
    description: 'A key technical training institute providing skilled workforce for the Peenya industrial hub.',
    facilities: ['Heavy Machinery Workshops', 'Library', 'Hostel'],
    admissionProcess: 'Merit-based on 10th Marks via NCVT MIS portal',
    entranceExams: ['None'],
    eligibility: '10th Pass (SSLC)',
    fees: {
      tuition: '₹2,500/yr',
      hostel: '₹5,000/yr',
      other: '₹500/yr'
    },
    hostelAvailable: false,
    scholarshipsAvailable: true,
    placement: {
      percentage: 95,
      highestPackage: '₹3 LPA',
      avgPackage: '₹1.8 LPA',
      topRecruiters: ['Peenya Industries Association', 'BOSCH', 'Wipro Infrastructure']
    },
    accreditation: 'NCVT, NABL',
    website: 'https://dgt.gov.in/',
    phone: '080-28394462',
    email: 'itipeenya@gmail.com',
    latitude: 13.0285,
    longitude: 77.5197,
    image: 'https://images.unsplash.com/photo-1621644788390-eec45c38229b?w=800&q=80',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Skill_India.jpg/220px-Skill_India.jpg',
    sourceName: 'NCVT MIS',
    sourceUrl: 'https://ncvtmis.gov.in/',
    verifiedAt: new Date(),
    isVerified: true
  },
  {
    name: 'Nettur Technical Training Foundation (NTTF) - Electronic City',
    categories: ['Diploma', 'Vocational', 'Polytechnic', 'ITI'],
    type: 'Private',
    institutionType: 'Vocational Training Institute',
    ownership: 'Private',
    state: 'Karnataka',
    district: 'Bengaluru Urban',
    city: 'Bengaluru',
    address: '40/40A, Electronic City Phase 1, Hosur Road, Bengaluru, Karnataka 560100',
    universityAffiliation: 'Autonomous',
    approvalBody: 'NSDC',
    establishedYear: 1959,
    courses: ['Diploma', 'Post Diploma', 'Certificate'],
    programs: ['Mechatronics', 'Electronics', 'Tool Engineering', 'IT & Computer Engg'],
    specializations: ['Robotics', 'Embedded Systems'],
    description: 'Renowned industry-focused technical training institution producing highly employable technical professionals.',
    facilities: ['Advanced Automation Labs', 'Library', 'Hostel', 'Sports'],
    admissionProcess: 'NTTF Entrance Exam',
    entranceExams: ['NTTF Entrance'],
    eligibility: '10th Pass / 12th Science',
    fees: {
      tuition: '₹80,000/yr',
      hostel: '₹60,000/yr',
      other: '₹10,000/yr'
    },
    hostelAvailable: true,
    scholarshipsAvailable: false,
    placement: {
      percentage: 100,
      highestPackage: '₹6 LPA',
      avgPackage: '₹3.5 LPA',
      topRecruiters: ['TCS', 'Wistron', 'Siemens', 'Foxconn']
    },
    accreditation: 'ISO 9001, NSDC',
    website: 'https://www.nttftrg.com',
    phone: '080-28520330',
    email: 'enquiry@nttf.co.in',
    latitude: 12.8452,
    longitude: 77.6601,
    image: 'https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?w=800&q=80',
    logo: 'https://www.nttftrg.com/images/nttf-logo.png',
    sourceName: 'NSDC / NTTF',
    sourceUrl: 'https://www.nttftrg.com/',
    verifiedAt: new Date(),
    isVerified: true
  }
];

async function seedDatabase() {
  try {
    await mongoose.connect(process.env.MONGODB_URI as string);
    console.log('✅ Connected to MongoDB');

    // Wipe existing colleges
    await College.deleteMany({});
    console.log('Cleared existing colleges.');

    // Insert new Karnataka colleges
    await College.insertMany(karnatakaColleges);
    console.log(`✅ Successfully seeded ${karnatakaColleges.length} Karnataka colleges across all categories!`);

    process.exit(0);
  } catch (error) {
    console.error('❌ Error seeding database:', error);
    process.exit(1);
  }
}

seedDatabase();
